function receiveMessageString(n){"use strict";var t={};t.data=n;t.source="";receiveMessage(t)}function receiveMessage(n){"use strict";var r,s,a,h,f,c,v,y,p,w,l;if(localCompartment===null&&(localCompartment=n.source),MSG_TYPE_ADPARAMS===n.data.substr(0,MSG_TYPE_ADPARAMS.length)){if(r=n.data.substr(MSG_TYPE_ADPARAMS.length+1),r!=="")try{adParams=JSON.parse(r)}catch(e){reportAdError("Ad params JSON parse error: "+e.message)}}else if(MSG_TYPE_PRMPARAMS===n.data.substr(0,MSG_TYPE_PRMPARAMS.length)){if(r=n.data.substr(MSG_TYPE_PRMPARAMS.length+1),r!=="")try{prmParams=JSON.parse(r)}catch(e){reportAdError("Prm params JSON parse error: "+e.message)}}else if(MSG_TYPE_APPPARAMS===n.data.substr(0,MSG_TYPE_APPPARAMS.length)){if(r=n.data.substr(MSG_TYPE_APPPARAMS.length+1),r!=="")try{appParams=JSON.parse(r)}catch(e){reportAdError("App options JSON parse error: "+e.message)}}else if(MSG_TYPE_SETID===n.data.substr(0,MSG_TYPE_SETID.length))adControlId=n.data.substr(MSG_TYPE_SETID.length+1);else if(MSG_TYPE_INIT!==n.data.substr(0,MSG_TYPE_INIT.length)&&typeof Ormma!="undefined"&&Ormma!==null){var u=n.data,t=null,i=null,o=u.indexOf(":");o<0?t=u:(t=u.substr(0,o),i=u.substr(o+1));t===MSG_TYPE_SETSIZE?(s=JSON.parse(i),Ormma._setSize(s.width,s.height)):t===MSG_TYPE_SETMAXSIZE?(a=JSON.parse(i),Ormma._maxSize=a):t===MSG_TYPE_SETSCREENSIZE?(h=JSON.parse(i),Ormma._setScreenSize(h.width,h.height)):t===MSG_TYPE_SETSTATE?Ormma._setState(i):t===MSG_TYPE_SETLOCALE?Ormma._setLocale(i):t===MSG_TYPE_SETSDKINFO?(f=JSON.parse(i),Ormma._setSdkVersion(f.sdkVersion,f.client,f.runtimeType)):t===MSG_TYPE_SETCAPABILITY?(c=JSON.parse(i),Ormma._setCapability(c.capability,c.value)):t===MSG_TYPE_SETPLACEMENTTYPE?Ormma._setPlacementType(i):t===MSG_TYPE_START?Ormma._init(i):t===MSG_TYPE_FIRESHAKE?Ormma._shake():t===MSG_TYPE_ORMMA_RESPONSE?Ormma._sendResponse(JSON.parse(i)):t===MSG_TYPE_UPDATETILTCOORDS?(v=JSON.parse(i),Ormma._tiltChange(v)):t===MSG_TYPE_VIEWABLECHANGE?(y=JSON.parse(i),Ormma._viewableChange(y.viewable)):t===MSG_TYPE_UPDATEORIENTATION?(p=JSON.parse(i),Ormma._setOrientation(p.orientation)):t===MSG_TYPE_SETNETWORK?Ormma._setNetwork(i):t===MSG_TYPE_WIREAPPEVENTS?(w=JSON.parse(i),_wireApplicationEvents(w)):t===MSG_TYPE_ERROR?(l=JSON.parse(i),Ormma._throwError(l.action,l.message)):t===MSG_TYPE_SETFOCUS&&i==="true"&&document.body.focus()}}function reportAdError(n){"use strict";console.log(n);postToLocal(MSG_TYPE_ERROR+":"+n)}function postToLocal(n){"use strict";localCompartment!=null&&window.external.notify(n)}function _wireApplicationEvents(n){"use strict";if(n!==null&&typeof n!="undefined"){var t=parseInt(n.events);(t&EVENT_TYPE_ENUM.PointerDown)!=0&&typeof applicationEventHandlers.onPointerDown!="function"?(applicationEventHandlers.onPointerDown=function(t){t.which===2&&n.preventDefault&&t.preventDefault();pointerDown=!0;postToLocal(MSG_TYPE_ONPOINTERDOWN+":"+JSON.stringify({clientX:t.clientX,clientY:t.clientY,pointerType:t.pointerType,which:t.which}))},window.addEventListener("MSPointerDown",applicationEventHandlers.onPointerDown,!1)):(t&EVENT_TYPE_ENUM.PointerDown)==0&&typeof applicationEventHandlers.onPointerDown=="function"&&(window.removeEventListener("MSPointerDown",applicationEventHandlers.onPointerDown,!1),applicationEventHandlers.onPointerDown=null);(t&EVENT_TYPE_ENUM.PointerUp)!=0&&typeof applicationEventHandlers.onPointerUp!="function"?(applicationEventHandlers.onPointerUp=function(n){n.type==="pointerout"?pointerDown&&(pointerDown=!1,postToLocal(MSG_TYPE_ONPOINTERUP)):(pointerDown=!1,postToLocal(MSG_TYPE_ONPOINTERUP))},window.addEventListener("MSPointerUp",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSPointerCancel",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSPointerOut",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSLostPointerCapture",applicationEventHandlers.onPointerUp,!1)):(t&EVENT_TYPE_ENUM.PointerUp)==0&&typeof applicationEventHandlers.onPointerUp=="function"&&(window.removeEventListener("MSPointerUp",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSPointerCancel",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSPointerOut",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSLostPointerCapture",applicationEventHandlers.onPointerUp,!1),applicationEventHandlers.onPointerUp=null);(t&EVENT_TYPE_ENUM.PointerMove)!=0&&typeof applicationEventHandlers.onPointerMove!="function"?(applicationEventHandlers.onPointerMove=function(n){postToLocal(MSG_TYPE_ONPOINTERMOVE+":"+JSON.stringify({clientX:n.clientX,clientY:n.clientY}))},window.addEventListener("MSPointerMove",applicationEventHandlers.onPointerMove,!1)):(t&EVENT_TYPE_ENUM.PointerMove)==0&&typeof applicationEventHandlers.onPointerMove=="function"&&(window.removeEventListener("MSPointerMove",applicationEventHandlers.onPointerMove,!1),applicationEventHandlers.onPointerMove=null);(t&EVENT_TYPE_ENUM.ManipulationStateChanged)!=0&&typeof applicationEventHandlers.onManipulationStateChanged!="function"?(applicationEventHandlers.onManipulationStateChanged=function(n){postToLocal(MSG_TYPE_ONMANIPSTATECHANGED+":"+JSON.stringify({lastState:n.lastState,currentState:n.currentState}))},window.addEventListener("MSManipulationStateChanged",applicationEventHandlers.onManipulationStateChanged,!1)):(t&EVENT_TYPE_ENUM.ManipulationStateChanged)==0&&typeof applicationEventHandlers.onManipulationStateChanged=="function"&&(window.removeEventListener("MSManipulationStateChanged",applicationEventHandlers.onManipulationStateChanged,!1),applicationEventHandlers.onManipulationStateChanged=null);(t&EVENT_TYPE_ENUM.MouseWheel)!=0&&typeof applicationEventHandlers.onMouseWheel!="function"?(applicationEventHandlers.onMouseWheel=function(t){n.preventDefault&&t.preventDefault();postToLocal(MSG_TYPE_ONMOUSEWHEEL+":"+JSON.stringify({clientX:t.clientX,clientY:t.clientY,ctrlKey:t.ctrlKey,wheelDelta:t.wheelDelta}))},window.addEventListener("mousewheel",applicationEventHandlers.onMouseWheel,!1)):(t&EVENT_TYPE_ENUM.MouseWheel)==0&&typeof applicationEventHandlers.onMouseWheel=="function"&&(window.removeEventListener("mousewheel",applicationEventHandlers.onMouseWheel,!1),applicationEventHandlers.onMouseWheel=null)}}window.onerror=function(n,t,i){"use strict";try{console.error("[msg:"+n+"][url:"+t+"][lineNumber:"+i+"]");window.external.notify("error:unhandled ad exception: "+n)}catch(r){}return!0};var localCompartment=null,adControlId=null,pointerDown,adParams=null,prmParams=null,appParams=null,MSG_TYPE_ADPARAMS="adParams",MSG_TYPE_PRMPARAMS="prmParams",MSG_TYPE_APPPARAMS="appParams",MSG_TYPE_INIT="init",MSG_TYPE_SETID="setId",MSG_TYPE_ERROR="error",MSG_TYPE_SETMAXSIZE="setMaxSize",MSG_TYPE_SETSCREENSIZE="setScreenSize",MSG_TYPE_SETSIZE="setSize",MSG_TYPE_SETSTATE="setState",MSG_TYPE_SETPLACEMENTTYPE="setPlacementType",MSG_TYPE_WIREAPPEVENTS="wireAppEvents",MSG_TYPE_START="ormmaStart",MSG_TYPE_ORMMA_RESPONSE="ormmaResponse",MSG_TYPE_FIRESHAKE="fireShake",MSG_TYPE_UPDATETILTCOORDS="updateTiltCoords",MSG_TYPE_UPDATEORIENTATION="updateOrienation",MSG_TYPE_VIEWABLECHANGE="viewableChange",MSG_TYPE_SETNETWORK="setNetwork",MSG_TYPE_SETLOCALE="setLocale",MSG_TYPE_SETSDKINFO="setSdkInfo",MSG_TYPE_SETCAPABILITY="setCapability",MSG_TYPE_SETFOCUS="setFocus",MSG_TYPE_ONPOINTERDOWN="MSPointerDown",MSG_TYPE_ONPOINTERUP="MSPointerUp",MSG_TYPE_ONPOINTERMOVE="MSPointerMove",MSG_TYPE_ONMOUSEWHEEL="MSMouseWheel",MSG_TYPE_ONMANIPSTATECHANGED="MSManipulationStateChanged",EVENT_TYPE_ENUM={All:-1,PointerDown:1,PointerUp:2,PointerMove:4,MouseWheel:16,ManipulationStateChanged:32},applicationEventHandlers={onPointerDown:null,onPointerUp:null,onMouseWheel:null,onPointerMove:null,onManipulationStateChanged:null};
// SIG // Begin signature block
// SIG // MIIdkgYJKoZIhvcNAQcCoIIdgzCCHX8CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFKpjhl5i8bQd
// SIG // HBrsOnhMdcMSqlmFoIIYVDCCBMIwggOqoAMCAQICEzMA
// SIG // AADA3iw9B5TkSXkAAAAAAMAwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE2MDkwNzE3
// SIG // NTg1MFoXDTE4MDkwNzE3NTg1MFowgbIxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDDAKBgNVBAsTA0FPQzEnMCUGA1UECxMe
// SIG // bkNpcGhlciBEU0UgRVNOOjdBQjUtMkRGMi1EQTNGMSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
// SIG // AQEA6IilUn5JVQAeBDnPfq/eZJd9prlzSE2HE22kbbiZ
// SIG // fjEMxJw9HlNiVF8dpiNOjjZ03xVt/WUDxdab1FpBwa0u
// SIG // pvKCsuxJuDpfdUSeSp8MtVb2Nk2sKoflccHQEUYDnhbR
// SIG // ZtEvj2vga17VVIU7RpdARjLChhECnQzRiQ9ufSKuO6jy
// SIG // 8NwppZRN/2BcNRhqCfQt68viO57cSIyWAS1wNdtr8Pdz
// SIG // jg/81hYdUlatgHoz8XIyrRx9oY6HkysJBXjDbSHpK1Er
// SIG // 4W7ghsVua+eCltGLrOKPN/dpfVc/JUhJ9o/04D06g+hG
// SIG // Zc5KcOeFUsHnXv78qoGSK0W2rdGwIW/HaGPLwwIDAQAB
// SIG // o4IBCTCCAQUwHQYDVR0OBBYEFBX+StozidMZhdVkWcTc
// SIG // U0EQT7c1MB8GA1UdIwQYMBaAFCM0+NlSRnAK7UD7dvuz
// SIG // K7DDNbMPMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9j
// SIG // cmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3Rz
// SIG // L01pY3Jvc29mdFRpbWVTdGFtcFBDQS5jcmwwWAYIKwYB
// SIG // BQUHAQEETDBKMEgGCCsGAQUFBzAChjxodHRwOi8vd3d3
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY3Jvc29m
// SIG // dFRpbWVTdGFtcFBDQS5jcnQwEwYDVR0lBAwwCgYIKwYB
// SIG // BQUHAwgwDQYJKoZIhvcNAQEFBQADggEBABniQLsyTEfp
// SIG // KLzIvESvy7X6yms1pUeS8dNoTPRhZjJNc1gknKX1WOsa
// SIG // n81hZZQhRwbTmiWai4lfe43zQi6RtD1C89uAlkpBu4yf
// SIG // pmWgkonGe2Qt21g4dc6XOeJZWFcsk5EVWMf5rXPRro6m
// SIG // 0vAgWYI2k/ybBAp7xgD1HC2LkhredwlNW1LojcLswIWo
// SIG // uIJXGMqt/+6jJpgLW52wmYUeckqDMuwcHcze9Hay7Wnw
// SIG // iUJ3HwB11Tua+kl+FP9ids71oQPJaoWbvUkbpRRkb3/N
// SIG // VU3/pOaydk4y+nWLUnIaKCeWFb1JOou231dFQTfMaWlI
// SIG // ZPI2wZ8YQzyiLw752ZYT7iYwggYBMIID6aADAgECAhMz
// SIG // AAAAxOmJ+HqBUOn/AAAAAADEMA0GCSqGSIb3DQEBCwUA
// SIG // MH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
// SIG // Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwHhcN
// SIG // MTcwODExMjAyMDI0WhcNMTgwODExMjAyMDI0WjB0MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUA
// SIG // A4IBDwAwggEKAoIBAQCIirgkwwePmoB5FfwmYPxyiCz6
// SIG // 9KOXiJZGt6PLX4kvOjMuHpF4+nypH4IBtXrLGrwDykbr
// SIG // xZn3+wQd8oUK/yJuofJnPcUnGOUoH/UElEFj7OO6FYzt
// SIG // E5o13jhwVG877K1FCTBJwb6PMJkMy3bJ93OVFnfRi7uU
// SIG // xwiFIO0eqDXxccLgdABLitLckevWeP6N+q1giD29uR+u
// SIG // Ype/xYSxkK7WryvTVPs12s1xkuYe/+xxa8t/CHZ04BBR
// SIG // SNTxAMhITKMHNeVZDf18nMjmWuOF9daaDx+OpuSEF8HW
// SIG // yp8dAcf9SKcTkjOXIUgy+MIkogCyvlPKg24pW4HvOG6A
// SIG // 87vsEwvrAgMBAAGjggGAMIIBfDAfBgNVHSUEGDAWBgor
// SIG // BgEEAYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUy9Zi
// SIG // hM9gOer/Z8Jc0si7q7fDE5gwUgYDVR0RBEswSaRHMEUx
// SIG // DTALBgNVBAsTBE1PUFIxNDAyBgNVBAUTKzIzMDAxMitj
// SIG // ODA0YjVlYS00OWI0LTQyMzgtODM2Mi1kODUxZmEyMjU0
// SIG // ZmMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggrBgEFBQcB
// SIG // AQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNVHRMBAf8E
// SIG // AjAAMA0GCSqGSIb3DQEBCwUAA4ICAQAGFh/bV8JQyCNP
// SIG // olF41+34/c291cDx+RtW7VPIaUcF1cTL7OL8mVuVXxE4
// SIG // KMAFRRPgmnmIvGar27vrAlUjtz0jeEFtrvjxAFqUmYoc
// SIG // zAmV0JocRDCppRbHukdb9Ss0i5+PWDfDThyvIsoQzdiC
// SIG // EKk18K4iyI8kpoGL3ycc5GYdiT4u/1cDTcFug6Ay67Sz
// SIG // L1BWXQaxFYzIHWO3cwzj1nomDyqWRacygz6WPldJdyOJ
// SIG // /rEQx4rlCBVRxStaMVs5apaopIhrlihv8cSu6r1FF8xi
// SIG // ToG1VBpHjpilbcBuJ8b4Jx/I7SCpC7HxzgualOJqnWmD
// SIG // oTbXbSD+hdX/w7iXNgn+PRTBmBSpwIbM74LBq1UkQxi1
// SIG // SIV4htD50p0/GdkUieeNn2gkiGg7qceATibnCCFMY/2c
// SIG // kxVNM7VWYE/XSrk4jv8u3bFfpENryXjPsbtrj4Nsh3Kq
// SIG // 6qX7n90a1jn8ZMltPgjlfIOxrbyjunvPllakeljLEkdi
// SIG // 0iHv/DzEMQv3Lz5kpTdvYFA/t0SQT6ALi75+WPbHZ4dh
// SIG // 256YxMiMy29H4cAulO2x9rAwbexqSajplnbIvQjE/jv1
// SIG // rnM3BrJWzxnUu/WUyocc8oBqAU+2G4Fzs9NbIj86WBjf
// SIG // iO5nxEmnL9wliz1e0Ow0RJEdvJEMdoI+78TYLaEEAo5I
// SIG // +e/dAs8DojCCBgcwggPvoAMCAQICCmEWaDQAAAAAABww
// SIG // DQYJKoZIhvcNAQEFBQAwXzETMBEGCgmSJomT8ixkARkW
// SIG // A2NvbTEZMBcGCgmSJomT8ixkARkWCW1pY3Jvc29mdDEt
// SIG // MCsGA1UEAxMkTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5MB4XDTA3MDQwMzEyNTMwOVoXDTIx
// SIG // MDQwMzEzMDMwOVowdzELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEh
// SIG // MB8GA1UEAxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // n6Fssd/bSJIqfGsuGeG94uPFmVEjUK3O3RhOJA/u0afR
// SIG // TK10MCAR6wfVVJUVSZQbQpKumFwwJtoAa+h7veyJBw/3
// SIG // DgSY8InMH8szJIed8vRnHCz8e+eIHernTqOhwSNTyo36
// SIG // Rc8J0F6v0LBCBKL5pmyTZ9co3EZTsIbQ5ShGLieshk9V
// SIG // UgzkAyz7apCQMG6H81kwnfp+1pez6CGXfvjSE/MIt1Nt
// SIG // UrRFkJ9IAEpHZhEnKWaol+TTBoFKovmEpxFHFAmCn4Tt
// SIG // VXj+AZodUAiFABAwRu233iNGu8QtVJ+vHnhBMXfMm987
// SIG // g5OhYQK1HQ2x/PebsgHOIktU//kFw8IgCwIDAQABo4IB
// SIG // qzCCAacwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
// SIG // IzT42VJGcArtQPt2+7MrsMM1sw8wCwYDVR0PBAQDAgGG
// SIG // MBAGCSsGAQQBgjcVAQQDAgEAMIGYBgNVHSMEgZAwgY2A
// SIG // FA6sgmBAVieX5SUT/CrhClOVWeSkoWOkYTBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHmCEHmtFqFKoKWt
// SIG // THNY9AcTLmUwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvbWljcm9zb2Z0cm9vdGNlcnQuY3JsMFQGCCsGAQUF
// SIG // BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3NvZnRS
// SIG // b290Q2VydC5jcnQwEwYDVR0lBAwwCgYIKwYBBQUHAwgw
// SIG // DQYJKoZIhvcNAQEFBQADggIBABCXisNcA0Q23em0rXfb
// SIG // znlRTQGxLnRxW20ME6vOvnuPuC7UEqKMbWK4VwLLTiAT
// SIG // UJndekDiV7uvWJoc4R0Bhqy7ePKL0Ow7Ae7ivo8KBciN
// SIG // SOLwUxXdT6uS5OeNatWAweaU8gYvhQPpkSokInD79vzk
// SIG // eJkuDfcH4nC8GE6djmsKcpW4oTmcZy3FUQ7qYlw/FpiL
// SIG // ID/iBxoy+cwxSnYxPStyC8jqcD3/hQoT38IKYY7w17gX
// SIG // 606Lf8U1K16jv+u8fQtCe9RTciHuMMq7eGVcWwEXChQO
// SIG // 0toUmPU8uWZYsy0v5/mFhsxRVuidcJRsrDlM1PZ5v6oY
// SIG // emIp76KbKTQGdxpiyT0ebR+C8AvHLLvPQ7Pl+ex9teOk
// SIG // qHQ1uE7FcSMSJnYLPFKMcVpGQxS8s7OwTWfIn0L/gHkh
// SIG // gJ4VMGboQhJeGsieIiHQQ+kr6bv0SMws1NgygEwmKkgk
// SIG // X1rqVu+m3pmdyjpvvYEndAYR7nYhv5uCwSdUtrFqPYmh
// SIG // dmG0bqETpr+qR/ASb/2KMmyy/t9RyIwjyWa9nR2HEmQC
// SIG // PS2vWY+45CHltbDKY7R4VAXUQS5QrJSwpXirs6CWdRrZ
// SIG // kocTdSIvMqgIbqBbjCW/oO+EyiHW6x5PyZruSeD3AWVv
// SIG // iQt9yGnI5m7qp5fOMSn/DsVbXNhNG6HY+i+ePy5VFmvJ
// SIG // E6P9MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
// SIG // hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
// SIG // MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5
// SIG // WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWdu
// SIG // aW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOC
// SIG // Ag8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGf
// SIG // Qhsqa+laUKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDI
// SIG // OdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv
// SIG // 2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13Y
// SIG // xC4Ddato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT
// SIG // +OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
// SIG // 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
// SIG // kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXD
// SIG // OW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
// SIG // GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4ji
// SIG // JV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bys
// SIG // AoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J64HLn
// SIG // JN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeB
// SIG // e+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx
// SIG // 7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu+HggWCwT
// SIG // XWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEA
// SIG // AaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1Ud
// SIG // DgQWBBRIbmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEE
// SIG // AYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYw
// SIG // DwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToC
// SIG // MZBDuRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBL
// SIG // hklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
// SIG // bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
// SIG // MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEF
// SIG // BQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
// SIG // aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNf
// SIG // MjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcu
// SIG // AzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMu
// SIG // aHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABf
// SIG // AHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0AZQBuAHQA
// SIG // LiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou
// SIG // 09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+
// SIG // vj/oCso7v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzS
// SIG // Gksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlE
// SIG // PXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6V
// SIG // oCo/KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu
// SIG // 5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
// SIG // STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
// SIG // mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38c
// SIG // bxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
// SIG // pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7f
// SIG // QccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AA
// SIG // KcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74v2u3
// SIG // S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8
// SIG // MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7
// SIG // qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJ
// SIG // UnMTDXpQzTGCBKowggSmAgEBMIGVMH4xCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2Rl
// SIG // IFNpZ25pbmcgUENBIDIwMTECEzMAAADE6Yn4eoFQ6f8A
// SIG // AAAAAMQwCQYFKw4DAhoFAKCBvjAZBgkqhkiG9w0BCQMx
// SIG // DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYK
// SIG // KwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU8ZQtCsCh
// SIG // NfZTlWVPaRrXWp+1Dx8wXgYKKwYBBAGCNwIBDDFQME6g
// SIG // DIAKAEEAZABTAEQAS6E+gDxodHRwOi8vZWR3ZWIvc2l0
// SIG // ZXMvSVNTRW5naW5lZXJpbmcvRW5nRnVuL1NpdGVQYWdl
// SIG // cy9Ib21lLmFzcHgwDQYJKoZIhvcNAQEBBQAEggEATqIK
// SIG // QUEv59elmrBqT1e/WKwQwtO6//vWOYRvhpobTV/hxpRN
// SIG // zHFL4lGVWMNOzFHbUVl9KSddtaS/Nj8v+m/+W+7vKqgG
// SIG // /R4U7eA74CFiCg0kfqWWf5yfa1Srh63IjecQ+AQJJKZ0
// SIG // TU+c9ezLc4cgXoSrj7jBX3Ye9huSTnmrjTFZzEUuAEhC
// SIG // V8DyHP2wLcnCXXRT+4Xkr0wvtLyONTo8hohLmsU+nBIo
// SIG // XHhKbZoB7kFh+PLfeicuzMAhBOiDredDQI0DVzCNQBMR
// SIG // SkSdxXSu71QBwVeInE5GYFhYP3GFr9Oo+yt6efa23Qtc
// SIG // 2OlVVBrekCevm+tmdh+x6bWjJS11j6GCAigwggIkBgkq
// SIG // hkiG9w0BCQYxggIVMIICEQIBATCBjjB3MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0ECEzMAAADA3iw9B5TkSXkAAAAAAMAw
// SIG // CQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG
// SIG // 9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDQwNjAyMjYw
// SIG // MVowIwYJKoZIhvcNAQkEMRYEFO6vIJl12xQWQj0kRuCO
// SIG // oqbQGszBMA0GCSqGSIb3DQEBBQUABIIBAI9iJrexjTpr
// SIG // GdqvvO6xpxfRvYnX3+Cl8e7CcP+KRdsQhwkgcxocOsww
// SIG // HaDRAtr5QvLT7PjjhOYW34dFIwcM2lvflYPM4EtRIG8b
// SIG // v8n9bWic8D8kzWxgcEW6yssPC6XHYkoxeLQgLyOvRtsX
// SIG // oOIGXDfUroKKKH4qiFo1Ptqh+zzK7NAc2+bhWHBQU3Tt
// SIG // 7DQuNUtLy33h6Prz/JJC4aQghm5jqOcJm28i4dpjOnm1
// SIG // my02wMF612ShiGTwfPXHN8iuXTtuBUXkMw0AOqU60ok5
// SIG // 1bPRN/ZqySEraiPvC6mBSka4Ifv4dlPCvk9iMTOlsgs0
// SIG // 8xBf8YAlrqqyY/ZEWS7+JoQ=
// SIG // End signature block
