"use strict";
/*!
  Copyright (C) Microsoft. All rights reserved.
  This library is supported for use in Windows Store apps only.
*/
function setScreenSize(n,t){var r=parseInt(n),i;r=r===NaN?-1:r;i=parseInt(t);i=i===NaN?-1:i;Ormma._setScreenSize(r,i)}function invokeInit(){Ormma._init()}function reportError(n,t){Ormma._throwError(n,t)}function setOrmmaState(n){Ormma._setState(n)}function setOrmmaPlacementType(n){Ormma._setPlacementType(n)}function setOrmmaLocale(n){Ormma._setLocale(n)}function setSize(n,t){var r=parseInt(n),i;r=r===NaN?-1:r;i=parseInt(t);i=i===NaN?-1:i;Ormma._setSize(r,i)}function setMaxSize(n,t){var r=parseInt(n),i;r=r===NaN?-1:r;i=parseInt(t);i=i===NaN?-1:i;Ormma._setMaxSize(r,i)}function setOrientation(n){var t=parseInt(n);t=t===NaN?-1:t;Ormma._setOrientation(t)}function fireShake(){Ormma._shake()}function updateTiltCoords(n,t,i){Ormma._tiltChange({x:n,y:t,z:i})}function fireViewable(n){var t=stringToBoolean(n);Ormma._viewableChange(t)}function viewableDataChange(n){Ormma._viewableDataChange(n)}function setCapability(n,t){Ormma._setCapability(n,stringToBoolean(t))}function stringToBoolean(n){return n.toLowerCase()==="true"?!0:!1}function fireResponse(n,t){var i={url:escape(n),response:escape(t)};Ormma._sendResponse(i)}function setNetwork(n){Ormma._setNetwork(n)}function setSdkVersion(n,t,i){Ormma._setSdkVersion(n,t,i)}function fireClickEvent(){Ormma._clicked()}var ORMMA_STATE_DEFAULT="default",ORMMA_STATE_EXPANDED="expanded",ORMMA_STATE_HIDDEN="hidden",ORMMA_STATE_LOADING="loading",ORMMA_STATE_RESIZED="resized",ORMMA_STATE_SUSPENDED="suspended",ORMMA_STATE_UNKNOWN="unknown",ORMMA_EVENT_ERROR="error",ORMMA_EVENT_HEADING_CHANGE="headingChange",ORMMA_EVENT_KEYBOARD_CHANGE="keyboardChange",ORMMA_EVENT_LOCATION_CHANGE="locationChange",ORMMA_EVENT_NETWORK_CHANGE="networkChange",ORMMA_EVENT_ORIENTATION_CHANGE="orientationChange",ORMMA_EVENT_READY="ready",ORMMA_EVENT_RESPONSE="response",ORMMA_EVENT_SCREEN_CHANGE="screenChange",ORMMA_EVENT_SHAKE="shake",ORMMA_EVENT_SIZE_CHANGE="sizeChange",ORMMA_EVENT_STATE_CHANGE="stateChange",ORMMA_EVENT_TILT_CHANGE="tiltChange",ORMMA_EVENT_VIEWABLE_CHANGE="viewableChange",MAPLE_EVENT_CLICK="click",MAPLE_EVENT_VIEWABLEDATA_CHANGE="viewableDataChange",ORMMA_FEATURE_AUDIO="audio",ORMMA_FEATURE_CALENDAR="calendar",ORMMA_FEATURE_CAMERA="camera",ORMMA_FEATURE_EMAIL="email",ORMMA_FEATURE_HEADING="heading",ORMMA_FEATURE_INLINEVIDEO="inlineVideo",ORMMA_FEATURE_LEVEL1="level-1",ORMMA_FEATURE_LEVEL2="level-2",ORMMA_FEATURE_LEVEL3="level-3",ORMMA_FEATURE_LOCATION="location",ORMMA_FEATURE_MAP="map",ORMMA_FEATURE_NETWORK="network",ORMMA_FEATURE_ORIENTATION="orientation",ORMMA_FEATURE_PHONE="phone",ORMMA_FEATURE_SCREEN="screen",ORMMA_FEATURE_SHAKE="shake",ORMMA_FEATURE_SMS="sms",ORMMA_FEATURE_TILT="tilt",ORMMA_FEATURE_VIDEO="video",ORMMA_API_VERSION="1.1.0",MRAID_API_VERSION="1.0",MAPLE_MAX_STATE_DATA_SIZE=65536,ORMMA_PLACEMENTTYPE_INLINE="inline",ORMMA_PLACEMENTTYPE_INTERSTITIAL="interstitial",MSG_TYPE_ADRENDERED="rendered",MSG_TYPE_CLOSE="close",MSG_TYPE_ERROR="error",MSG_TYPE_EXPAND="expand",MSG_TYPE_GETORIENTATION="getorientation",MSG_TYPE_GETTILT="gettilt",MSG_TYPE_HIDE="hide",MSG_TYPE_LISTENER="listener",MSG_TYPE_OPEN="web",MSG_TYPE_REFRESH="refresh",MSG_TYPE_REQUEST="request",MSG_TYPE_RESIZE="resize",MSG_TYPE_SETEXPANDPROPERTIES="setexpandproperties",MSG_TYPE_SETUSERENGAGED="setuserengaged",MSG_TYPE_SHAKE="shake",MSG_TYPE_SHOW="show",MSG_TYPE_TILT="tilt",MSG_TYPE_USECUSTOMCLOSE="usecustomclose",MSG_TYPE_VALUESTART="start",MSG_TYPE_VALUESTOP="stop",MSG_TYPE_VIEWABLECHANGE="viewableChange",MSG_TYPE_VIEWABLEDATACHANGE="viewableDataChange",MSG_TYPE_LOGAPIUSAGE="logapiusage",FUNC_NAME_ADDEVENTLISTENER="addEventListener",FUNC_NAME_REMOVEEVENTLISTENER="removeEventListener",FUNC_NAME_EXPAND="expand",FUNC_NAME_SUPPORTS="supports",FUNC_NAME_GETSIZE="getSize",FUNC_NAME_OPEN="open",FUNC_NAME_CLOSE="close",FUNC_NAME_GETEXPANDPROPERTIES="getExpandProperties",FUNC_NAME_GETPLACEMENTTYPE="getPlacementType",FUNC_NAME_SETEXPANDPROPERTIES="setExpandProperties",FUNC_NAME_USECUSTOMCLOSE="useCustomClose",ADBROKER_PREBID_HEADER_APPID="appId",ADBROKER_PREBID_HEADER_APPGUID="appGuid",ADBROKER_PREBID_HEADER_DOMAIN="domain";(function(){function f(){this.listeners=[]}function n(){}function u(n){return typeof n=="undefined"||n===null||n<=0?!1:!0}function t(n){window.msAdSDK&&typeof window.msAdSDK.notify=="function"?window.msAdSDK.notify(n):window.external.notify(n)}function e(n,t,i){window.maple.app===undefined&&(window.maple.app={});window.maple.app.appId=n;window.maple.app.appGuid=t;window.maple.app.domain=i}function r(t,r){var f,u,o;if(n("raising event "+t+" with data "+r),i.listeners[t]!==null&&typeof i.listeners[t]!="undefined")try{f=i.listeners[t].slice();switch(t){case ORMMA_EVENT_ERROR:for(u=0;u<f.length;u++)f[u](r.message,r.action);break;case ORMMA_EVENT_NETWORK_CHANGE:for(u=0;u<f.length;u++)f[u](r.online,r.connection);break;case ORMMA_EVENT_ORIENTATION_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_READY:for(u=0;u<f.length;u++)f[u]();break;case ORMMA_EVENT_SCREEN_CHANGE:for(u=0;u<f.length;u++)f[u](r.width,r.height);break;case ORMMA_EVENT_SHAKE:for(u=0;u<f.length;u++)f[u]();break;case ORMMA_EVENT_SIZE_CHANGE:for(u=0;u<f.length;u++)f[u](r.width,r.height);break;case ORMMA_EVENT_STATE_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_TILT_CHANGE:for(u=0;u<f.length;u++)f[u](r.x,r.y,r.z);break;case ORMMA_EVENT_VIEWABLE_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_RESPONSE:for(u=0;u<f.length;u++)f[u](unescape(r.url),unescape(r.response));break;case MAPLE_EVENT_CLICK:for(u=0;u<f.length;u++)f[u]();break;case MAPLE_EVENT_VIEWABLEDATA_CHANGE:for(o=JSON.parse(r),e(o[ADBROKER_PREBID_HEADER_APPID],o[ADBROKER_PREBID_HEADER_APPGUID],o[ADBROKER_PREBID_HEADER_DOMAIN]),u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_HEADING_CHANGE:case ORMMA_EVENT_KEYBOARD_CHANGE:case ORMMA_EVENT_LOCATION_CHANGE:default:return!1}}catch(s){n("exception thrown while firing event: "+s.message)}else n("no listeners for event "+t)}var i=new f;window.ORMMA=window.ormma=window.Ormma=window.MAPLE=window.maple=window.Maple={_maxSize:{width:0,height:0},_dimensions:{},_defaultDimensions:{},_screenSize:null,_tiltCapability:!1,_shakeCapability:!1,_expandProperties:{width:0,height:0,useCustomClose:!1,lockOrientation:!1,isModal:!0},_shakeProperties:{},_resizeProperties:{transition:"none"},_placementType:ORMMA_PLACEMENTTYPE_INLINE,_state:ORMMA_STATE_LOADING,_locale:null,_location:null,_orientation:-1,_lastTiltCoords:{x:0,y:0,z:0},_lastNetworkState:ORMMA_STATE_UNKNOWN,_sdkInfo:null,_msOrientationModes:{portaitPrimary:{ieProperty:"portrait-primary",orientationDegrees:0},landscapePrimary:{ieProperty:"landscape-primary",orientationDegrees:270},portaitSecondary:{ieProperty:"portrait-secondary",orientationDegrees:180},landscapeSecondary:{ieProperty:"landscape-secondary",orientationDegrees:90},unknown:{ieProperty:"",orientationDegrees:-1}},addEventListener:function(r,u){if((i.listeners[r]===null||typeof i.listeners[r]=="undefined")&&(i.listeners[r]=[]),r!==ORMMA_EVENT_TILT_CHANGE||this._tiltCapability){if(r===ORMMA_EVENT_SHAKE&&!this._shakeCapability){this._throwError("shake","shake capability is not supported, event listener not added");return}}else{this._throwError("tilt","tilt capability is not supported, event listener not added");return}n("adding listener for "+r);i.listeners[r].push(u);r===ORMMA_EVENT_TILT_CHANGE?t(MSG_TYPE_TILT+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===ORMMA_EVENT_SHAKE?t(MSG_TYPE_SHAKE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===ORMMA_EVENT_ORIENTATION_CHANGE?t(MSG_TYPE_GETORIENTATION+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===ORMMA_EVENT_VIEWABLE_CHANGE?t(MSG_TYPE_VIEWABLECHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===MAPLE_EVENT_VIEWABLEDATA_CHANGE&&t(MSG_TYPE_VIEWABLEDATACHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART)},removeEventListener:function(r,u){if(n("removing listener for "+r),i.listeners[r]!==null&&typeof i.listeners[r]!="undefined"){if(u===undefined||u===null||u==="")i.listeners[r].length=0;else for(var e=i.listeners[r],f=0;f<e.length;f++)if(e[f]===u){e.splice(f,1);break}if(i.listeners[r]===null||typeof i.listeners[r]=="undefined"||i.listeners[r].length===0)if(r===ORMMA_EVENT_TILT_CHANGE){if(!this._tiltCapability){this._throwError("tilt","tilt capability is not supported, no event listener");return}n("stopping tilt device for event: "+r+" (no more client listeners)");t(MSG_TYPE_TILT+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)}else if(r===ORMMA_EVENT_SHAKE){if(!this._shakeCapability){this._throwError("shake","shake capability is not supported, no event listener");return}n("stopping shake device for event: "+r+" (no more client listeners)");t(MSG_TYPE_SHAKE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)}else r===ORMMA_EVENT_ORIENTATION_CHANGE?(n("stopping orientation changed event: "+r+" (no more client listeners)"),t(MSG_TYPE_GETORIENTATION+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)):r===ORMMA_EVENT_VIEWABLE_CHANGE?(n("stopping viewable changed event: "+r+" (no more client listeners)"),t(MSG_TYPE_VIEWABLECHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)):r===MAPLE_EVENT_CLICK?n("stopping clickEvent : "+r+" (no more client listeners)"):r===MAPLE_EVENT_VIEWABLEDATA_CHANGE&&(n("stopping viewable data changed event: "+r+" (no more client listeners)"),t(MSG_TYPE_VIEWABLEDATACHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP))}},close:function(){n("sending close request");t(MSG_TYPE_CLOSE)},expand:function(i,r){var u,f;if((typeof i=="undefined"||i===null)&&(i=""),!(this._state===ORMMA_STATE_DEFAULT||this._state===ORMMA_STATE_RESIZED)){reportError(FUNC_NAME_EXPAND,"can only expand from resized or default states");return}(typeof r=="undefined"||r===null)&&(r=!0);typeof this._expandProperties=="object"&&(u=JSON.stringify(this._expandProperties),t(MSG_TYPE_SETEXPANDPROPERTIES+":"+u));n("sending expand request");f={url:i,islegacy:r};t(MSG_TYPE_EXPAND+":"+JSON.stringify(f))},getDefaultPosition:function(){return this._defaultDimensions},getExpandProperties:function(){return this._expandProperties?this._expandProperties:Ormma._expandProperties},getNetwork:function(){return this._lastNetworkState},getOrientation:function(){var n=this._msOrientationToOrmmaDegrees(window.screen.msOrientation);return this._orientation=this._orientation===n?this._orientation:n,this._orientation},getPlacementType:function(){return this._placementType},getScreenSize:function(){return this._screenSize===null&&(this._screenSize={width:screen.availWidth,height:screen.availHeight}),this._screenSize},getShakeProperties:function(){return this._shakeProperties},getSize:function(){return typeof this._dimensions=="undefined"&&(this._dimensions={}),this._dimensions},getState:function(){return this._state},getTilt:function(){if(n("calling getTilt"),!this._tiltCapability){this._throwError("tilt","tilt capability is not supported");return}return t(MSG_TYPE_TILT+":"+MSG_TYPE_GETTILT+"="+MSG_TYPE_REFRESH),this._lastTiltCoords},getVersion:function(){return ORMMA_API_VERSION},hide:function(){n("calling hide");t(MSG_TYPE_HIDE)},isViewable:function(){n("[not impl] isViewable called")},open:function(i){n("sending website request: "+i);var r=JSON.stringify({url:i});t(MSG_TYPE_OPEN+":"+r)},request:function(n,i){var r={url:n,display:typeof i!="undefined"&&i!==null?i:"ignore"},u=JSON.stringify(r);return t(MSG_TYPE_REQUEST+":"+u),!1},resize:function(i,r){if(i>this._maxSize.width||i<0){this._throwError("resize","width is greater than max allowed width ("+this._maxSize.width+") or less than zero.");return}if(r>this._maxSize.height||r<0){this._throwError("resize","height is greater than max allowed height  ("+this._maxSize.height+") or less than zero.");return}n("calling resize:width="+i+"&height="+r);var u={width:i,height:r};t(MSG_TYPE_RESIZE+":"+JSON.stringify(u))},setExpandProperties:function(i){var r,f;this._expandProperties=typeof i!="object"?{}:i;r=typeof this.getScreenSize=="function"?this.getScreenSize():window.ormma.getScreenSize();this._expandProperties.width=u(this._expandProperties.width)&&this._expandProperties.width<r.width?this._expandProperties.width:r.width;this._expandProperties.height=u(this._expandProperties.height)&&this._expandProperties.height<r.height?this._expandProperties.height:r.height;this._expandProperties.useCustomClose=typeof this._expandProperties.useCustomClose=="undefined"?!1:this._expandProperties.useCustomClose;this._expandProperties.lockOrientation=typeof this._expandProperties.lockOrientation=="undefined"?!1:this._expandProperties.lockOrientation;this._expandProperties.isModal=!0;f=JSON.stringify(this._expandProperties);n("setting expand properties: "+f);t(MSG_TYPE_SETEXPANDPROPERTIES+":"+f)},setShakeProperties:function(t){this._shakeProperties=typeof t!="object"?{}:t;var i=JSON.stringify(this._shakeProperties);n("setting shake properties: "+i)},show:function(){n("calling show");t(MSG_TYPE_SHOW)},supports:function(n){switch(n){case ORMMA_FEATURE_SCREEN:case ORMMA_FEATURE_ORIENTATION:case ORMMA_FEATURE_LEVEL1:case ORMMA_FEATURE_LEVEL2:case ORMMA_FEATURE_NETWORK:case ORMMA_FEATURE_INLINEVIDEO:return!0;case ORMMA_FEATURE_SHAKE:return this._shakeCapability;case ORMMA_FEATURE_TILT:return this._tiltCapability;case ORMMA_FEATURE_PHONE:case ORMMA_FEATURE_SMS:case ORMMA_FEATURE_EMAIL:case ORMMA_FEATURE_LOCATION:case ORMMA_FEATURE_HEADING:case ORMMA_FEATURE_CALENDAR:case ORMMA_FEATURE_AUDIO:case ORMMA_FEATURE_VIDEO:case ORMMA_FEATURE_LEVEL3:default:return!1}},useCustomClose:function(i){typeof i=="boolean"?(n("calling usecustomclose:"+i),typeof this._expandProperties=="object"&&(this._expandProperties.useCustomClose=i),t(MSG_TYPE_USECUSTOMCLOSE+":"+i)):reportError("useCustomClose","parameter 'flag' is not a boolean value")},adAnchorReady:function(){var n=document.getElementById("msMainAdDiv");n!==null&&(n.style.visibility="visible");t(MSG_TYPE_ADRENDERED)},adError:function(n,i){var r,u,f;r=typeof n=="string"&&n!==null?n:"unknown action";u=typeof i=="string"&&i!==null?i:"an unknown error occurred.";f=JSON.stringify({action:r,message:u});t(MSG_TYPE_ERROR+":"+f)},getLocale:function(){if(this._locale!==null)return this._locale},getSdkVersion:function(){if(this._sdkInfo!==null)return this._sdkInfo},hasListenerForClickEvent:function(){return typeof i.listeners[MAPLE_EVENT_CLICK]!="undefined"&&i.listeners[MAPLE_EVENT_CLICK]!==null&&i.listeners[MAPLE_EVENT_CLICK].length>0?!0:!1},setUserEngaged:function(i){this._isUserEngaged=typeof i=="boolean"?i:!1;n("setting user engaged: "+this._isUserEngaged);t(MSG_TYPE_SETUSERENGAGED+":engaged="+this._isUserEngaged)},_clicked:function(){r(MAPLE_EVENT_CLICK,null)},_tiltChange:function(n){this._lastTiltCoords=n;r(ORMMA_EVENT_TILT_CHANGE,n)},_shake:function(){r(ORMMA_EVENT_SHAKE)},_viewableChange:function(n){window.mraid._isViewable=n;r(ORMMA_EVENT_VIEWABLE_CHANGE,n)},_viewableDataChange:function(n){r(MAPLE_EVENT_VIEWABLEDATA_CHANGE,n)},_sendResponse:function(n){r(ORMMA_EVENT_RESPONSE,n)},_throwError:function(n,t){var i={message:t,action:n};r(ORMMA_EVENT_ERROR,i)},_init:function(){n("Ormma is ready");this._state==ORMMA_STATE_LOADING&&Ormma._setState(ORMMA_STATE_DEFAULT);r(ORMMA_EVENT_READY,null);typeof window.ORMMAReady=="function"&&(n("Ormma calling ORMMAReady()"),window.ORMMAReady())},_setOrientation:function(n){var t=this._orientation;this._orientation=n;t!==this._orientation&&r(ORMMA_EVENT_ORIENTATION_CHANGE,this._orientation)},_setPlacementType:function(n){n===ORMMA_PLACEMENTTYPE_INLINE?this._placementType=n:n===ORMMA_PLACEMENTTYPE_INTERSTITIAL&&(this._placementType=n)},_setState:function(n){var t=this._state;this._state=n;t!==n&&r(ORMMA_EVENT_STATE_CHANGE,this._state)},_setLocale:function(n){this._locale=n},_setSize:function(n,t){typeof this._dimensions=="undefined"&&(this._dimensions={});var i=typeof this._dimensions.width=="undefined"?0:this._dimensions.width,u=typeof this._dimensions.height=="undefined"?0:this._dimensions.height;this._dimensions.width=n;this._dimensions.height=t;(i!==n||u!==t)&&r(ORMMA_EVENT_SIZE_CHANGE,this._dimensions)},_setSdkVersion:function(n,t,i){this._sdkInfo={sdkVersion:n,client:t,runtimeType:i,appName:navigator.appName,appVersion:navigator.appVersion,userAgent:navigator.userAgent,platform:navigator.platform}},_setCapability:function(n,t){typeof t=="boolean"&&(n===ORMMA_FEATURE_TILT?this._tiltCapability=t:n===ORMMA_FEATURE_SHAKE&&(this._shakeCapability=t))},_setMaxSize:function(n,t){typeof this._maxSize=="undefined"&&(this._maxSize={});this._maxSize.width=n;this._maxSize.height=t},_setScreenSize:function(n,t){(this._screenSize===null||typeof this._screenSize=="undefined")&&(this._screenSize={});var i=typeof this._screenSize.width=="undefined"?0:this._screenSize.width,u=typeof this._screenSize.height=="undefined"?0:this._screenSize.height;this._screenSize.width=n;this._screenSize.height=t;this._expandProperties.width===i&&(this._expandProperties.width=n);this._expandProperties.height===u&&(this._expandProperties.height=t);this.setExpandProperties(this._expandProperties);(i!==this._screenSize.width||u!==this._screenSize.height)&&r(ORMMA_EVENT_SCREEN_CHANGE,this._screenSize)},_setNetwork:function(t){n("setting network state: "+t);typeof this._lastNetworkState=="undefined"&&(this._lastNetworkState="");t!==this._lastNetworkState&&(this._lastNetworkState=t,r(ORMMA_EVENT_NETWORK_CHANGE,{online:t!=="offline",connection:t}))},_msOrientationToOrmmaDegrees:function(n){switch(n){case this._msOrientationModes.landscapePrimary.ieProperty:return this._msOrientationModes.landscapePrimary.orientationDegrees;case this._msOrientationModes.landscapeSecondary.ieProperty:return this._msOrientationModes.landscapeSecondary.orientationDegrees;case this._msOrientationModes.portaitSecondary.ieProperty:return this._msOrientationModes.portaitSecondary.orientationDegrees;case this._msOrientationModes.portaitPrimary.ieProperty:return this._msOrientationModes.portaitPrimary.orientationDegrees;default:return this._msOrientationModes.unknown.orientationDegrees}}};window.mraid=window.MRAID=window.Mraid={_isViewable:!1,addEventListener:function(n,t){this._mraidSupportedEvts===null&&(this._mraidSupportedEvts=this._initEventList());this._mraidSupportedEvts[n]&&window.ormma.addEventListener(n,t)},removeEventListener:function(n,t){this._mraidSupportedEvts===null&&(this._mraidSupportedEvts=this._initEventList());this._mraidSupportedEvts[n]&&window.ormma.removeEventListener(n,t)},expand:function(n){Object.getOwnPropertyNames(this);window.ormma.expand(n,!1)},getState:function(){return window.ormma._state},getVersion:function(){return MRAID_API_VERSION},isViewable:function(){return window.mraid._isViewable},_mraidSupportedEvts:null,_initEventList:function(){var n=[];return n[ORMMA_EVENT_ERROR]=n[ORMMA_EVENT_READY]=n[ORMMA_EVENT_STATE_CHANGE]=n[MAPLE_EVENT_VIEWABLEDATA_CHANGE]=n[ORMMA_EVENT_VIEWABLE_CHANGE]=!0,n},supports:function(n){return window.ormma.supports(n)},getSize:function(){return window.ormma.getSize()},open:function(n){return window.ormma.open(n)},close:function(){return window.ormma.close()},getExpandProperties:function(){return window.ormma.getExpandProperties()},getPlacementType:function(){return window.ormma.getPlacementType()},setExpandProperties:function(n){return window.ormma.setExpandProperties(n)},useCustomClose:function(n){return window.ormma.useCustomClose(n)}}})();
// SIG // Begin signature block
// SIG // MIIdkgYJKoZIhvcNAQcCoIIdgzCCHX8CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFEqw6Bvi5lbB
// SIG // FnJ8SxgVmwvymbRRoIIYVDCCBMIwggOqoAMCAQICEzMA
// SIG // AADDO7gQ1qt1nIQAAAAAAMMwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE2MDkwNzE3
// SIG // NTg1MVoXDTE4MDkwNzE3NTg1MVowgbIxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDDAKBgNVBAsTA0FPQzEnMCUGA1UECxMe
// SIG // bkNpcGhlciBEU0UgRVNOOkQyMzYtMzdEQS05NzYxMSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
// SIG // AQEAojhtsAxlWY+WR4ApdGWhMcuh2UGfU9rrqT7sarYl
// SIG // qlx9qCI++thqjHNST2B5KRKOWpcoFnbwdw+hUqqQPGpf
// SIG // phiUzJLZQPsnbLSz0a+ggaBBfoZukQc8FZbDfc+gVaac
// SIG // CGVrdpRFRuq9WFtcta29HeBbAPKsEUiNLAfLAMPSB14v
// SIG // yeCXepJUL8NpuqC15fQu9/9Q5XTz2WBjkw0PfEcSGmHs
// SIG // L5LJzam5ZrxaTsfCrnnZMZeI7QCpdBf9vkKkX1N9jgIg
// SIG // omBYGSIDjweAPFGx5iyMp+6TaraJuDajImc/RuAZuW8C
// SIG // C4RJWHGTzKvz9R69/P1qAA/fVgJt1haV0hWXowIDAQAB
// SIG // o4IBCTCCAQUwHQYDVR0OBBYEFHN3F3hjEPEFeCG2juDx
// SIG // MPOFhxeoMB8GA1UdIwQYMBaAFCM0+NlSRnAK7UD7dvuz
// SIG // K7DDNbMPMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9j
// SIG // cmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3Rz
// SIG // L01pY3Jvc29mdFRpbWVTdGFtcFBDQS5jcmwwWAYIKwYB
// SIG // BQUHAQEETDBKMEgGCCsGAQUFBzAChjxodHRwOi8vd3d3
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY3Jvc29m
// SIG // dFRpbWVTdGFtcFBDQS5jcnQwEwYDVR0lBAwwCgYIKwYB
// SIG // BQUHAwgwDQYJKoZIhvcNAQEFBQADggEBAEjjytZ7alsG
// SIG // iFpzSDWPi5Zh0OEPPIekzjdGhPunGdka4wVFOPUk5MkN
// SIG // pYLyqZiJEGFiW7jUYeuSCdRyJ8IQ/F1ndH9CVwCK805S
// SIG // 9M8N0nW67cmfbD+Dcaso0Nt8QYiP3ddwq7X0wFZRmCGN
// SIG // QIZfNPtChsrlMyS04vd+dP4B2iNCc94q8KyfobcRdVFv
// SIG // zU9AGCckWHtnpfSYYHrnXijimr930AZcwC0JpOBJKMqt
// SIG // 5riRxqKn3jaOM7D/zPlkOqATJVKvP+PbIP68rj9BHlbT
// SIG // Ynj7sT5l+Yuip86Xd6z4Cj0vvU6tXSi7bNSuK46QEqCk
// SIG // rPFG7968EEsNDv803dW3PBIwggYBMIID6aADAgECAhMz
// SIG // AAAAxOmJ+HqBUOn/AAAAAADEMA0GCSqGSIb3DQEBCwUA
// SIG // MH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
// SIG // Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwHhcN
// SIG // MTcwODExMjAyMDI0WhcNMTgwODExMjAyMDI0WjB0MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUA
// SIG // A4IBDwAwggEKAoIBAQCIirgkwwePmoB5FfwmYPxyiCz6
// SIG // 9KOXiJZGt6PLX4kvOjMuHpF4+nypH4IBtXrLGrwDykbr
// SIG // xZn3+wQd8oUK/yJuofJnPcUnGOUoH/UElEFj7OO6FYzt
// SIG // E5o13jhwVG877K1FCTBJwb6PMJkMy3bJ93OVFnfRi7uU
// SIG // xwiFIO0eqDXxccLgdABLitLckevWeP6N+q1giD29uR+u
// SIG // Ype/xYSxkK7WryvTVPs12s1xkuYe/+xxa8t/CHZ04BBR
// SIG // SNTxAMhITKMHNeVZDf18nMjmWuOF9daaDx+OpuSEF8HW
// SIG // yp8dAcf9SKcTkjOXIUgy+MIkogCyvlPKg24pW4HvOG6A
// SIG // 87vsEwvrAgMBAAGjggGAMIIBfDAfBgNVHSUEGDAWBgor
// SIG // BgEEAYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUy9Zi
// SIG // hM9gOer/Z8Jc0si7q7fDE5gwUgYDVR0RBEswSaRHMEUx
// SIG // DTALBgNVBAsTBE1PUFIxNDAyBgNVBAUTKzIzMDAxMitj
// SIG // ODA0YjVlYS00OWI0LTQyMzgtODM2Mi1kODUxZmEyMjU0
// SIG // ZmMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggrBgEFBQcB
// SIG // AQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNVHRMBAf8E
// SIG // AjAAMA0GCSqGSIb3DQEBCwUAA4ICAQAGFh/bV8JQyCNP
// SIG // olF41+34/c291cDx+RtW7VPIaUcF1cTL7OL8mVuVXxE4
// SIG // KMAFRRPgmnmIvGar27vrAlUjtz0jeEFtrvjxAFqUmYoc
// SIG // zAmV0JocRDCppRbHukdb9Ss0i5+PWDfDThyvIsoQzdiC
// SIG // EKk18K4iyI8kpoGL3ycc5GYdiT4u/1cDTcFug6Ay67Sz
// SIG // L1BWXQaxFYzIHWO3cwzj1nomDyqWRacygz6WPldJdyOJ
// SIG // /rEQx4rlCBVRxStaMVs5apaopIhrlihv8cSu6r1FF8xi
// SIG // ToG1VBpHjpilbcBuJ8b4Jx/I7SCpC7HxzgualOJqnWmD
// SIG // oTbXbSD+hdX/w7iXNgn+PRTBmBSpwIbM74LBq1UkQxi1
// SIG // SIV4htD50p0/GdkUieeNn2gkiGg7qceATibnCCFMY/2c
// SIG // kxVNM7VWYE/XSrk4jv8u3bFfpENryXjPsbtrj4Nsh3Kq
// SIG // 6qX7n90a1jn8ZMltPgjlfIOxrbyjunvPllakeljLEkdi
// SIG // 0iHv/DzEMQv3Lz5kpTdvYFA/t0SQT6ALi75+WPbHZ4dh
// SIG // 256YxMiMy29H4cAulO2x9rAwbexqSajplnbIvQjE/jv1
// SIG // rnM3BrJWzxnUu/WUyocc8oBqAU+2G4Fzs9NbIj86WBjf
// SIG // iO5nxEmnL9wliz1e0Ow0RJEdvJEMdoI+78TYLaEEAo5I
// SIG // +e/dAs8DojCCBgcwggPvoAMCAQICCmEWaDQAAAAAABww
// SIG // DQYJKoZIhvcNAQEFBQAwXzETMBEGCgmSJomT8ixkARkW
// SIG // A2NvbTEZMBcGCgmSJomT8ixkARkWCW1pY3Jvc29mdDEt
// SIG // MCsGA1UEAxMkTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5MB4XDTA3MDQwMzEyNTMwOVoXDTIx
// SIG // MDQwMzEzMDMwOVowdzELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEh
// SIG // MB8GA1UEAxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // n6Fssd/bSJIqfGsuGeG94uPFmVEjUK3O3RhOJA/u0afR
// SIG // TK10MCAR6wfVVJUVSZQbQpKumFwwJtoAa+h7veyJBw/3
// SIG // DgSY8InMH8szJIed8vRnHCz8e+eIHernTqOhwSNTyo36
// SIG // Rc8J0F6v0LBCBKL5pmyTZ9co3EZTsIbQ5ShGLieshk9V
// SIG // UgzkAyz7apCQMG6H81kwnfp+1pez6CGXfvjSE/MIt1Nt
// SIG // UrRFkJ9IAEpHZhEnKWaol+TTBoFKovmEpxFHFAmCn4Tt
// SIG // VXj+AZodUAiFABAwRu233iNGu8QtVJ+vHnhBMXfMm987
// SIG // g5OhYQK1HQ2x/PebsgHOIktU//kFw8IgCwIDAQABo4IB
// SIG // qzCCAacwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
// SIG // IzT42VJGcArtQPt2+7MrsMM1sw8wCwYDVR0PBAQDAgGG
// SIG // MBAGCSsGAQQBgjcVAQQDAgEAMIGYBgNVHSMEgZAwgY2A
// SIG // FA6sgmBAVieX5SUT/CrhClOVWeSkoWOkYTBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHmCEHmtFqFKoKWt
// SIG // THNY9AcTLmUwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvbWljcm9zb2Z0cm9vdGNlcnQuY3JsMFQGCCsGAQUF
// SIG // BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3NvZnRS
// SIG // b290Q2VydC5jcnQwEwYDVR0lBAwwCgYIKwYBBQUHAwgw
// SIG // DQYJKoZIhvcNAQEFBQADggIBABCXisNcA0Q23em0rXfb
// SIG // znlRTQGxLnRxW20ME6vOvnuPuC7UEqKMbWK4VwLLTiAT
// SIG // UJndekDiV7uvWJoc4R0Bhqy7ePKL0Ow7Ae7ivo8KBciN
// SIG // SOLwUxXdT6uS5OeNatWAweaU8gYvhQPpkSokInD79vzk
// SIG // eJkuDfcH4nC8GE6djmsKcpW4oTmcZy3FUQ7qYlw/FpiL
// SIG // ID/iBxoy+cwxSnYxPStyC8jqcD3/hQoT38IKYY7w17gX
// SIG // 606Lf8U1K16jv+u8fQtCe9RTciHuMMq7eGVcWwEXChQO
// SIG // 0toUmPU8uWZYsy0v5/mFhsxRVuidcJRsrDlM1PZ5v6oY
// SIG // emIp76KbKTQGdxpiyT0ebR+C8AvHLLvPQ7Pl+ex9teOk
// SIG // qHQ1uE7FcSMSJnYLPFKMcVpGQxS8s7OwTWfIn0L/gHkh
// SIG // gJ4VMGboQhJeGsieIiHQQ+kr6bv0SMws1NgygEwmKkgk
// SIG // X1rqVu+m3pmdyjpvvYEndAYR7nYhv5uCwSdUtrFqPYmh
// SIG // dmG0bqETpr+qR/ASb/2KMmyy/t9RyIwjyWa9nR2HEmQC
// SIG // PS2vWY+45CHltbDKY7R4VAXUQS5QrJSwpXirs6CWdRrZ
// SIG // kocTdSIvMqgIbqBbjCW/oO+EyiHW6x5PyZruSeD3AWVv
// SIG // iQt9yGnI5m7qp5fOMSn/DsVbXNhNG6HY+i+ePy5VFmvJ
// SIG // E6P9MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
// SIG // hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
// SIG // MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5
// SIG // WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWdu
// SIG // aW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOC
// SIG // Ag8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGf
// SIG // Qhsqa+laUKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDI
// SIG // OdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv
// SIG // 2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13Y
// SIG // xC4Ddato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT
// SIG // +OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
// SIG // 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
// SIG // kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXD
// SIG // OW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
// SIG // GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4ji
// SIG // JV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bys
// SIG // AoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J64HLn
// SIG // JN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeB
// SIG // e+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx
// SIG // 7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu+HggWCwT
// SIG // XWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEA
// SIG // AaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1Ud
// SIG // DgQWBBRIbmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEE
// SIG // AYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYw
// SIG // DwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToC
// SIG // MZBDuRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBL
// SIG // hklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
// SIG // bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
// SIG // MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEF
// SIG // BQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
// SIG // aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNf
// SIG // MjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcu
// SIG // AzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMu
// SIG // aHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABf
// SIG // AHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0AZQBuAHQA
// SIG // LiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou
// SIG // 09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+
// SIG // vj/oCso7v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzS
// SIG // Gksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlE
// SIG // PXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6V
// SIG // oCo/KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu
// SIG // 5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
// SIG // STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
// SIG // mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38c
// SIG // bxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
// SIG // pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7f
// SIG // QccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AA
// SIG // KcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74v2u3
// SIG // S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8
// SIG // MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7
// SIG // qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJ
// SIG // UnMTDXpQzTGCBKowggSmAgEBMIGVMH4xCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2Rl
// SIG // IFNpZ25pbmcgUENBIDIwMTECEzMAAADE6Yn4eoFQ6f8A
// SIG // AAAAAMQwCQYFKw4DAhoFAKCBvjAZBgkqhkiG9w0BCQMx
// SIG // DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYK
// SIG // KwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUOR8tvG+9
// SIG // sBUtutAfLyHXbbg/NIowXgYKKwYBBAGCNwIBDDFQME6g
// SIG // DIAKAEEAZABTAEQAS6E+gDxodHRwOi8vZWR3ZWIvc2l0
// SIG // ZXMvSVNTRW5naW5lZXJpbmcvRW5nRnVuL1NpdGVQYWdl
// SIG // cy9Ib21lLmFzcHgwDQYJKoZIhvcNAQEBBQAEggEAGYZX
// SIG // tMECuQEbibuiKJ3EeHHAU30TpZs42L59lhmC9RWShoAk
// SIG // MqBMOdMRvbKgzh2GT1LCiANQJyk40p9Le8x3sw2Gz15C
// SIG // b8tOWWuJGqGS/+EWsS0tE61Uf9WYY7dRu85V68HY1pJo
// SIG // dJ1MuI9WNLikM9aubnJ54qsxomt0IuDhHQDKI0rax3Fl
// SIG // esMDLEPFWnU0761bnCGAwrkw1HVOnsju+qqBl3mH4LUV
// SIG // 18Lw3oDqE4WOdI1eQeO+j91Y5TqzA0KSql+p8mIMTrd5
// SIG // j5+YZGw2zBHchIC/Y/TBcfYZ8y2qznVJYkzFgDsRdzk9
// SIG // ZWs40JKs9QDXFBZAupG9xgyfoDlDRaGCAigwggIkBgkq
// SIG // hkiG9w0BCQYxggIVMIICEQIBATCBjjB3MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0ECEzMAAADDO7gQ1qt1nIQAAAAAAMMw
// SIG // CQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG
// SIG // 9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDQwNjAyMjU1
// SIG // NlowIwYJKoZIhvcNAQkEMRYEFDkYmWgF1PQJ8oCFLksS
// SIG // 8Anla7uCMA0GCSqGSIb3DQEBBQUABIIBAElbKSa/8z7n
// SIG // 4lh7XhlbQrVypOEkbEUbXwstpdt/lG/hYp3jns113Djn
// SIG // bS1lYP8IiHJ7Y+0RnugoJfMpFIq43WnGWtZhsRYrPT1J
// SIG // D47lVE5F+9shpAnoQ3mtf/6XvhFaeVKYA95Y2BNR0+gU
// SIG // NTuGF22bYr+3aa2XZi3wOuPhkMBu9IG5yUcTjYRi4ow/
// SIG // wTzguCv25/BVD0wnkpWqa29Md8y5gpAbOrmVCbJbILOg
// SIG // 2MbAFL3zK2p8ishCN7a9Rvw9z4IQFdS1fkCZr7YWg1T7
// SIG // jQ2hhE3Rkg962dsk9QzJcsw/zKvpr/zPM1RsHW3h8DqN
// SIG // Qo/v4UTii/Sl7HMzYrpln94=
// SIG // End signature block
