/*!
  Copyright (C) Microsoft. All rights reserved.
  This library is supported for use in Windows Store apps only.
  NOTE: please make sure this file is in sync with https://videoadssdk.azurewebsites.net/api/vpaid?code=oRMOeXB1sSJe12kLg/9JQRBZZM42xQ/dP1abFOwAq7tVZD4DMe13wQ==
*/
(function(){"use strict";function l(){this._listeners=[];this._adSize={width:0,height:0};this._setSdkVersion("unknown","unknown","unknown");this._masterVolumeLevel=0;this._masterVolumeMuted=!1}var r=2,h=0,c=r+"."+h,n;window.onerror=function(n,t,i){try{console.error("[msg:"+n+"][url:"+t+"][lineNumber:"+i+"]");typeof _msVpaidImpl=="function"&&_msVpaidImpl.reportAdError("unhandled JS exception: "+n)}catch(r){}return!0};window.onload=function(){if(typeof getVPAIDAd!="function"){_msVpaidImpl.reportAdError("getVPAIDAd function not defined");return}var t=getVPAIDAd();if(!t){_msVpaidImpl.reportAdError("getVPAIDAd did not return an ad");return}window._msVpaidInstance=new n(t)};window._msReceiveMessageFromAdSdk=function(t){n.log("message from SDK: "+t);window._msVpaidInstance&&window._msVpaidInstance.receiveMessageFromAdSdk(t);window.Maple&&window.Maple.receiveMessageFromAdSdk(t)};n=function(t){if(n.log("instantiating VpaidImpl"),this._creative=t,this._adParameters=null,!n.isValidVpaidCreative(t)){n.reportAdError("ad is not a valid VPAID creative");return}var i=t.handshakeVersion(c);if(!n.isVersionSupported(i)){n.reportAdError("ad requires VPAID version "+i+", sdk supports "+c);return}this._setupEventHandlers(this._creative)};n.prototype={DEFAULT_DESIRED_BITRATE:2e3,initAd:function(t,i,r,u,f,e){n.log("initializing vpaid ad");e||(e={slot:document.querySelector("#msVpaidSlot"),videoSlot:document.querySelector("#msVpaidVideo")});this._creative.initAd(t,i,r,u,f,e)},receiveMessageFromAdSdk:function(t){var u,f,o;if(t&&typeof t=="string"){var r=t,i=null,e=null;try{u=r.indexOf(":");u<0?i=r:(i=r.substr(0,u),e=r.substr(u+1));i==="InitAd"?this._receiveMessageInitAd(e):i==="StartAd"?this.startAd():i==="StopAd"?this.stopAd():i==="PauseAd"?this.pauseAd():i==="ResumeAd"?this.resumeAd():i==="ResizeAd"?(f=JSON.parse(e),this.resizeAd(f.width,f.height,f.viewMode)):i==="SetAdVolume"&&(o=50,this.setAdVolume(o))}catch(s){n.reportAdError("error handling message of type "+i)}}},_receiveMessageInitAd:function(t){try{var i=JSON.parse(t),r=typeof i.desiredBitrate=="number"?i.desiredBitrate:this.DEFAULT_DESIRED_BITRATE,u=typeof i.width=="number"?i.width:0,f=typeof i.height=="number"?i.height:0,e=typeof i.viewMode=="string"?i.viewMode:"fullscreen",o={AdParameters:i.adParameters};this.initAd(u,f,e,r,o,null)}catch(s){n.reportAdError("unable to parse JSON for initAd")}},setAdVolume:function(n){this._creative.setAdVolume(n)},startAd:function(){n.log("startAd");this._creative.startAd()},stopAd:function(){this._creative.stopAd()},resizeAd:function(t,i,r){n.log("resizing ad to "+t+" x "+i+", "+r);this._creative.resizeAd(t,i,r)},pauseAd:function(){this._creative.pauseAd()},resumeAd:function(){this._creative.resumeAd()},_setupEventHandlers:function(t){t&&(n.log("adding event handlers"),t.subscribe(this._adStartedHandler,"AdStarted",this),t.subscribe(this._adStoppedHandler,"AdStopped",this),t.subscribe(this._adSkippedHandler,"AdSkipped",this),t.subscribe(this._adLoadedHandler,"AdLoaded",this),t.subscribe(this._adLinearChangeHandler,"AdLinearChange",this),t.subscribe(this._adSizeChangeHandler,"AdSizeChange",this),t.subscribe(this._adExpandedChangeHandler,"AdExpandedChange",this),t.subscribe(this._adSkippableStateChangeHandler,"AdSkippableStateChange",this),t.subscribe(this._adDurationChangeHandler,"AdDurationChange",this),t.subscribe(this._adRemainingTimeChangeHandler,"AdRemainingTimeChange",this),t.subscribe(this._adVolumeChangeHandler,"AdVolumeChange",this),t.subscribe(this._adImpressionHandler,"AdImpression",this),t.subscribe(this._adClickThruHandler,"AdClickThru",this),t.subscribe(this._adInteractionHandler,"AdInteraction",this),t.subscribe(this._adVideoStartHandler,"AdVideoStart",this),t.subscribe(this._adVideoFirstQuartileHandler,"AdVideoFirstQuartile",this),t.subscribe(this._adVideoMidpointHandler,"AdVideoMidpoint",this),t.subscribe(this._adVideoThirdQuartileHandler,"AdVideoThirdQuartile",this),t.subscribe(this._adVideoCompleteHandler,"AdVideoComplete",this),t.subscribe(this._adUserAcceptInvitationHandler,"AdUserAcceptInvitation",this),t.subscribe(this._adUserMinimizeHandler,"AdUserMinimize",this),t.subscribe(this._adUserCloseHandler,"AdUserClose",this),t.subscribe(this._adPausedHandler,"AdPaused",this),t.subscribe(this._adPlayingHandler,"AdPlaying",this),t.subscribe(this._adErrorHandler,"AdError",this),t.subscribe(this._adLogHandler,"AdLog",this))},_adLoadedHandler:function(){n.log("ad has been loaded");n.sendMessageToAdSdk("AdLoaded")},_adPausedHandler:function(){n.log("ad paused");n.sendMessageToAdSdk("AdPaused")},_adPlayingHandler:function(){n.log("ad playing");n.sendMessageToAdSdk("AdPlaying")},_adErrorHandler:function(t){var i,r;typeof t!="string"&&(i=t,t=i!==null&&typeof i=="object"&&i.message!=="undefined"?"ad error message was: [object]: "+i.message:"ad error message was: "+typeof t);n.log("ad error: "+t);r={message:t};n.sendMessageToAdSdk("(VpaidError) AdError:"+JSON.stringify(r))},_adLogHandler:function(t){var i,r;typeof t!="string"&&(i=t,t=i!==null&&typeof i=="object"&&i.message!=="undefined"?"AdLog:: [object]: "+i.message:"AdLog::"+typeof t);n.log("ad log: "+t);r={message:t};n.sendMessageToAdSdk("AdLog:"+JSON.stringify(r))},_adUserAcceptInvitationHandler:function(){n.log("AdUserAcceptInvitation");n.sendMessageToAdSdk("AdUserAcceptInvitation")},_adUserMinimizeHandler:function(){n.log("AdUserMinimize");n.sendMessageToAdSdk("AdUserMinimize")},_adUserCloseHandler:function(){n.log("AdUserClose");n.sendMessageToAdSdk("AdUserClose")},_adSkippableStateChangeHandler:function(){n.log("ad Skippable State Changed to: "+this._creative.getAdSkippableState());n.sendMessageToAdSdk("AdSkippableStateChange")},_adExpandedChangeHandler:function(){n.log("ad Expanded Changed to: "+this._creative.getAdExpanded());n.sendMessageToAdSdk("AdExpanded")},_adSizeChangeHandler:function(){n.log("ad size changed to: w="+this._creative.getAdWidth()+" h="+this._creative.getAdHeight());var t={width:this._creative.getAdWidth(),height:this._creative.getAdHeight()};n.sendMessageToAdSdk("AdSizeChange:"+JSON.stringify(t))},_adDurationChangeHandler:function(){n.log("ad duration changed to: "+this._creative.getAdDuration());var t={duration:this._creative.getAdDuration()};n.sendMessageToAdSdk("AdDurationChange:"+JSON.stringify(t))},_adRemainingTimeChangeHandler:function(){var t={remainingTime:this._creative.getAdRemainingTime()};n.sendMessageToAdSdk("AdRemainingTimeChange:"+JSON.stringify(t))},_adImpressionHandler:function(){n.log("ad impression");n.sendMessageToAdSdk("AdImpression")},_adClickThruHandler:function(t,i,r){n.log("click-through");typeof t!="string"&&(t="");typeof i!="string"&&(i="");typeof r!="boolean"&&(r=r==="true"?!0:!1);var u={url:t,id:i,playerHandles:r};n.sendMessageToAdSdk("AdClickThru:"+JSON.stringify(u))},_adInteractionHandler:function(){n.log("ad interaction");n.sendMessageToAdSdk("AdInteraction")},_adVideoStartHandler:function(){n.log("video started");n.sendMessageToAdSdk("AdVideoStart")},_adVideoFirstQuartileHandler:function(){n.log("video 25% completed");n.sendMessageToAdSdk("AdVideoFirstQuartile")},_adVideoMidpointHandler:function(){n.log("video 50% completed");n.sendMessageToAdSdk("AdVideoMidpoint")},_adVideoThirdQuartileHandler:function(){n.log("video 75% completed");n.sendMessageToAdSdk("AdVideoThirdQuartile")},_adVideoCompleteHandler:function(){n.log("video completed");n.sendMessageToAdSdk("AdVideoComplete")},_adLinearChangeHandler:function(){n.log("ad linear has changed: "+this._creative.getAdLinear());n.sendMessageToAdSdk("AdLinearChange")},_adStartedHandler:function(){n.log("ad started");n.sendMessageToAdSdk("AdStarted")},_adStoppedHandler:function(){n.log("ad stopped");n.sendMessageToAdSdk("AdStopped")},_adSkippedHandler:function(){n.log("ad skipped");n.sendMessageToAdSdk("AdSkipped")},_adVolumeChangeHandler:function(){n.log("ad volume changed to - "+this._creative.getAdVolume());n.sendMessageToAdSdk("AdVolumeChange")}};n.MSG_TYPE_ERROR="AdError";n.reportAdError=function(t){n.log("AD ERROR: "+t);var i={message:t};n.sendMessageToAdSdk(n.MSG_TYPE_ERROR+":"+JSON.stringify(i))};n.sendMessageToAdSdk=function(n){window.external.notify(n)};n.isVersionSupported=function(n){if(!n||typeof n!="string")return!1;var t=n.split(".").map(function(n){return parseInt(n,10)}),i=t.length>0?t[0]:NaN,u=t.length>1?t[1]:0;return isNaN(i)||isNaN(u)?!1:i>r?!1:i===r&&u>h?!1:!0};n.isValidVpaidCreative=function(n){return typeof n=="object"&&n!==null&&n.handshakeVersion&&typeof n.handshakeVersion=="function"&&n.initAd&&typeof n.initAd=="function"&&n.startAd&&typeof n.startAd=="function"&&n.stopAd&&typeof n.stopAd=="function"&&n.skipAd&&typeof n.skipAd=="function"&&n.resizeAd&&typeof n.resizeAd=="function"&&n.pauseAd&&typeof n.pauseAd=="function"&&n.resumeAd&&typeof n.resumeAd=="function"&&n.expandAd&&typeof n.expandAd=="function"&&n.collapseAd&&typeof n.collapseAd=="function"&&n.subscribe&&typeof n.subscribe=="function"&&n.unsubscribe&&typeof n.unsubscribe=="function"?!0:!1};n.log=function(){};window._msVpaidImpl=n;var t="viewableChange",i="viewableDataChange",u="ViewableChange",f="ViewableDataChange",a="SdkVersion",e="appId",o="appGuid",s="domain";l.prototype={addEventListener:function(r,e){(r===i||r===t)&&r&&typeof e=="function"&&((this._listeners[r]===null||typeof this._listeners[r]=="undefined")&&(this._listeners[r]=[]),n.log("adding listener for "+r),this._listeners[r].push(e),r===t?n.sendMessageToAdSdk(u+":"+JSON.stringify({listener:"start"})):r===i&&n.sendMessageToAdSdk(f+":"+JSON.stringify({listener:"start"})))},removeEventListener:function(r,e){var s,o;if(n.log("removing listener for "+r),this._listeners&&this._listeners[r]!==null&&typeof this._listeners[r]!="undefined"){if(e===undefined||e===null||e==="")this._listeners[r].length=0;else for(s=this._listeners[r],o=0;o<s.length;o++)if(s[o]===e){s.splice(o,1);break}(this._listeners[r]===null||typeof this._listeners[r]=="undefined"||this._listeners[r].length===0)&&(r===t?(n.log("stopping viewable changed event: "+r+" (no more client listeners)"),n.sendMessageToAdSdk(u+":"+JSON.stringify({listener:"stop"}))):r===i&&(n.log("stopping viewable data changed event: "+r+" (no more client listeners)"),n.sendMessageToAdSdk(f+":"+JSON.stringify({listener:"stop"}))))}},getSize:function(){return typeof this._adSize=="undefined"&&(this._adSize={}),this._adSize},getSdkVersion:function(){return this._sdkInfo||(this._sdkInfo={}),this._sdkInfo},receiveMessageFromAdSdk:function(r){var y,w,h;if(r&&typeof r=="string"){var v=r,c=null,l=null;try{y=v.indexOf(":");y<0?c=v:(c=v.substr(0,y),l=v.substr(y+1));c===u?(w=l?l.toLowerCase()==="true":!1,this._fireEvent(t,w)):c===f?(h=JSON.parse(l),this._setAppPrebidHeader(h[e],h[o],h[s]),this._fireEvent(i,h)):c==="ResizeAd"?(h=JSON.parse(l),this._setSize(h.width,h.height)):c===a&&(h=JSON.parse(l),this._setSdkVersion(h.sdkVersion,h.client,h.runtimeType),this._setAppPrebidHeader(h[e],h[o],h[s]))}catch(p){n.log("Maple error handling message of type: "+c+": "+(p&&p.message?p.message:"unknown"));n.reportAdError("Maple error handling message of type "+c)}}},_setSize:function(t,i){n.log("setting Maple size to "+t+" x "+i);this._adSize={width:t,height:i}},_setSdkVersion:function(t,i,r){this._sdkInfo={sdkVersion:t,client:i,runtimeType:r,appName:navigator.appName,appVersion:navigator.appVersion,userAgent:navigator.userAgent,platform:navigator.platform};n.log("Ad SDK version: "+t+", "+i+", "+r)},_setAppPrebidHeader:function(n,t,i){this.app===undefined&&(this.app={});this.app.appId=n;this.app.appGuid=t;this.app.domain=i},_fireEvent:function(r,u){if(n.log("raising event "+r+" with data "+u),this._listeners[r]!==null&&typeof this._listeners[r]!="undefined")try{var h=this._listeners[r].slice(),f;switch(r){case t:case i:for(this._masterVolumeLevel=u.adMasterVolume,this._masterVolumeMuted=u.adMasterVolumeMuted,this._setAppPrebidHeader(u[e],u[o],u[s]),f=0;f<h.length;f++)h[f](u);break;default:return}}catch(c){n.log("exception thrown while firing event: "+c.message)}else n.log("no listeners for event "+r)}};window.Maple=window.maple=window.MAPLE=new l})();
// SIG // Begin signature block
// SIG // MIIdkgYJKoZIhvcNAQcCoIIdgzCCHX8CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFB6xtbSl7tJA
// SIG // 8cTjPlajceNQ0GgxoIIYVDCCBMIwggOqoAMCAQICEzMA
// SIG // AAC+pA/1yaUO4TAAAAAAAL4wDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE2MDkwNzE3
// SIG // NTg0OVoXDTE4MDkwNzE3NTg0OVowgbIxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDDAKBgNVBAsTA0FPQzEnMCUGA1UECxMe
// SIG // bkNpcGhlciBEU0UgRVNOOjg0M0QtMzdGNi1GMTA0MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
// SIG // AQEAkTnxY0VcSpoEwrTdeFOo8atbwCu0wYt/aktgSFOe
// SIG // l8NSHjhTY4O28OjvAzC69OBoYmvGrYepY98mmz0sl4mF
// SIG // C635P+z5C1AKg26+ghQP5Lr6C2JnjxIGCoCNr7a7qtOT
// SIG // AARmMsOFqVHy7XIQjYgWFmsMq3Xh2sPNMb31K2+3AwFP
// SIG // LLfeGyJIMm6Ggze396CM0B6ssaJPF0kmmSSk8qjbRLQ6
// SIG // O6emSd8oAmvfJQpP0o6VZy5BpV9JSd8vx9hTNvIDZ30G
// SIG // UDvD3tCAr9ygqYuAj6sfSxLj4EKCa2Cue9yNSyZW401f
// SIG // pe91Bz26NsONFvS9UhruVFq8DW+rWapOEcBLyQIDAQAB
// SIG // o4IBCTCCAQUwHQYDVR0OBBYEFBxuDV2ibEKdPt8dvS4u
// SIG // 58KXNJB/MB8GA1UdIwQYMBaAFCM0+NlSRnAK7UD7dvuz
// SIG // K7DDNbMPMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9j
// SIG // cmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3Rz
// SIG // L01pY3Jvc29mdFRpbWVTdGFtcFBDQS5jcmwwWAYIKwYB
// SIG // BQUHAQEETDBKMEgGCCsGAQUFBzAChjxodHRwOi8vd3d3
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY3Jvc29m
// SIG // dFRpbWVTdGFtcFBDQS5jcnQwEwYDVR0lBAwwCgYIKwYB
// SIG // BQUHAwgwDQYJKoZIhvcNAQEFBQADggEBAG5gcWy3gqsb
// SIG // GRTzGBc/9tAzD/ENdnR/9XDULq7ETB9GINHE8C59SBdw
// SIG // xsqXx2ScG8pfR1jVX/tiatOczGo348YhLvpIc5jJwPfw
// SIG // SdbrT8EdJz8si2zftCBgTH2C3iAHQvNXtAlvU6VqXOpR
// SIG // /44Fm4b4lLeDL7dg0DFiEO1sCQHQXhowp7SyDT8QvUZh
// SIG // 8rBRnsTLF0voWDUds/4fz5r7DcIauwrTOmzO9Wb2BWgU
// SIG // gprXUPPykAj4jemnG9lf9vFbmRMI6txhQCX3CjL4bLHs
// SIG // EYAmLCsYb1mR1JAa1MVp7L8TQjlj6XpwYlUmJeZ0/Ywa
// SIG // FaEwwoTCE0d+YK//w5oc17MwggYBMIID6aADAgECAhMz
// SIG // AAAAxOmJ+HqBUOn/AAAAAADEMA0GCSqGSIb3DQEBCwUA
// SIG // MH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
// SIG // Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwHhcN
// SIG // MTcwODExMjAyMDI0WhcNMTgwODExMjAyMDI0WjB0MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUA
// SIG // A4IBDwAwggEKAoIBAQCIirgkwwePmoB5FfwmYPxyiCz6
// SIG // 9KOXiJZGt6PLX4kvOjMuHpF4+nypH4IBtXrLGrwDykbr
// SIG // xZn3+wQd8oUK/yJuofJnPcUnGOUoH/UElEFj7OO6FYzt
// SIG // E5o13jhwVG877K1FCTBJwb6PMJkMy3bJ93OVFnfRi7uU
// SIG // xwiFIO0eqDXxccLgdABLitLckevWeP6N+q1giD29uR+u
// SIG // Ype/xYSxkK7WryvTVPs12s1xkuYe/+xxa8t/CHZ04BBR
// SIG // SNTxAMhITKMHNeVZDf18nMjmWuOF9daaDx+OpuSEF8HW
// SIG // yp8dAcf9SKcTkjOXIUgy+MIkogCyvlPKg24pW4HvOG6A
// SIG // 87vsEwvrAgMBAAGjggGAMIIBfDAfBgNVHSUEGDAWBgor
// SIG // BgEEAYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUy9Zi
// SIG // hM9gOer/Z8Jc0si7q7fDE5gwUgYDVR0RBEswSaRHMEUx
// SIG // DTALBgNVBAsTBE1PUFIxNDAyBgNVBAUTKzIzMDAxMitj
// SIG // ODA0YjVlYS00OWI0LTQyMzgtODM2Mi1kODUxZmEyMjU0
// SIG // ZmMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggrBgEFBQcB
// SIG // AQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNVHRMBAf8E
// SIG // AjAAMA0GCSqGSIb3DQEBCwUAA4ICAQAGFh/bV8JQyCNP
// SIG // olF41+34/c291cDx+RtW7VPIaUcF1cTL7OL8mVuVXxE4
// SIG // KMAFRRPgmnmIvGar27vrAlUjtz0jeEFtrvjxAFqUmYoc
// SIG // zAmV0JocRDCppRbHukdb9Ss0i5+PWDfDThyvIsoQzdiC
// SIG // EKk18K4iyI8kpoGL3ycc5GYdiT4u/1cDTcFug6Ay67Sz
// SIG // L1BWXQaxFYzIHWO3cwzj1nomDyqWRacygz6WPldJdyOJ
// SIG // /rEQx4rlCBVRxStaMVs5apaopIhrlihv8cSu6r1FF8xi
// SIG // ToG1VBpHjpilbcBuJ8b4Jx/I7SCpC7HxzgualOJqnWmD
// SIG // oTbXbSD+hdX/w7iXNgn+PRTBmBSpwIbM74LBq1UkQxi1
// SIG // SIV4htD50p0/GdkUieeNn2gkiGg7qceATibnCCFMY/2c
// SIG // kxVNM7VWYE/XSrk4jv8u3bFfpENryXjPsbtrj4Nsh3Kq
// SIG // 6qX7n90a1jn8ZMltPgjlfIOxrbyjunvPllakeljLEkdi
// SIG // 0iHv/DzEMQv3Lz5kpTdvYFA/t0SQT6ALi75+WPbHZ4dh
// SIG // 256YxMiMy29H4cAulO2x9rAwbexqSajplnbIvQjE/jv1
// SIG // rnM3BrJWzxnUu/WUyocc8oBqAU+2G4Fzs9NbIj86WBjf
// SIG // iO5nxEmnL9wliz1e0Ow0RJEdvJEMdoI+78TYLaEEAo5I
// SIG // +e/dAs8DojCCBgcwggPvoAMCAQICCmEWaDQAAAAAABww
// SIG // DQYJKoZIhvcNAQEFBQAwXzETMBEGCgmSJomT8ixkARkW
// SIG // A2NvbTEZMBcGCgmSJomT8ixkARkWCW1pY3Jvc29mdDEt
// SIG // MCsGA1UEAxMkTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5MB4XDTA3MDQwMzEyNTMwOVoXDTIx
// SIG // MDQwMzEzMDMwOVowdzELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEh
// SIG // MB8GA1UEAxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // n6Fssd/bSJIqfGsuGeG94uPFmVEjUK3O3RhOJA/u0afR
// SIG // TK10MCAR6wfVVJUVSZQbQpKumFwwJtoAa+h7veyJBw/3
// SIG // DgSY8InMH8szJIed8vRnHCz8e+eIHernTqOhwSNTyo36
// SIG // Rc8J0F6v0LBCBKL5pmyTZ9co3EZTsIbQ5ShGLieshk9V
// SIG // UgzkAyz7apCQMG6H81kwnfp+1pez6CGXfvjSE/MIt1Nt
// SIG // UrRFkJ9IAEpHZhEnKWaol+TTBoFKovmEpxFHFAmCn4Tt
// SIG // VXj+AZodUAiFABAwRu233iNGu8QtVJ+vHnhBMXfMm987
// SIG // g5OhYQK1HQ2x/PebsgHOIktU//kFw8IgCwIDAQABo4IB
// SIG // qzCCAacwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
// SIG // IzT42VJGcArtQPt2+7MrsMM1sw8wCwYDVR0PBAQDAgGG
// SIG // MBAGCSsGAQQBgjcVAQQDAgEAMIGYBgNVHSMEgZAwgY2A
// SIG // FA6sgmBAVieX5SUT/CrhClOVWeSkoWOkYTBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHmCEHmtFqFKoKWt
// SIG // THNY9AcTLmUwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvbWljcm9zb2Z0cm9vdGNlcnQuY3JsMFQGCCsGAQUF
// SIG // BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3NvZnRS
// SIG // b290Q2VydC5jcnQwEwYDVR0lBAwwCgYIKwYBBQUHAwgw
// SIG // DQYJKoZIhvcNAQEFBQADggIBABCXisNcA0Q23em0rXfb
// SIG // znlRTQGxLnRxW20ME6vOvnuPuC7UEqKMbWK4VwLLTiAT
// SIG // UJndekDiV7uvWJoc4R0Bhqy7ePKL0Ow7Ae7ivo8KBciN
// SIG // SOLwUxXdT6uS5OeNatWAweaU8gYvhQPpkSokInD79vzk
// SIG // eJkuDfcH4nC8GE6djmsKcpW4oTmcZy3FUQ7qYlw/FpiL
// SIG // ID/iBxoy+cwxSnYxPStyC8jqcD3/hQoT38IKYY7w17gX
// SIG // 606Lf8U1K16jv+u8fQtCe9RTciHuMMq7eGVcWwEXChQO
// SIG // 0toUmPU8uWZYsy0v5/mFhsxRVuidcJRsrDlM1PZ5v6oY
// SIG // emIp76KbKTQGdxpiyT0ebR+C8AvHLLvPQ7Pl+ex9teOk
// SIG // qHQ1uE7FcSMSJnYLPFKMcVpGQxS8s7OwTWfIn0L/gHkh
// SIG // gJ4VMGboQhJeGsieIiHQQ+kr6bv0SMws1NgygEwmKkgk
// SIG // X1rqVu+m3pmdyjpvvYEndAYR7nYhv5uCwSdUtrFqPYmh
// SIG // dmG0bqETpr+qR/ASb/2KMmyy/t9RyIwjyWa9nR2HEmQC
// SIG // PS2vWY+45CHltbDKY7R4VAXUQS5QrJSwpXirs6CWdRrZ
// SIG // kocTdSIvMqgIbqBbjCW/oO+EyiHW6x5PyZruSeD3AWVv
// SIG // iQt9yGnI5m7qp5fOMSn/DsVbXNhNG6HY+i+ePy5VFmvJ
// SIG // E6P9MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
// SIG // hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
// SIG // MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5
// SIG // WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWdu
// SIG // aW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOC
// SIG // Ag8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGf
// SIG // Qhsqa+laUKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDI
// SIG // OdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv
// SIG // 2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13Y
// SIG // xC4Ddato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT
// SIG // +OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
// SIG // 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
// SIG // kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXD
// SIG // OW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
// SIG // GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4ji
// SIG // JV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bys
// SIG // AoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J64HLn
// SIG // JN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeB
// SIG // e+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx
// SIG // 7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu+HggWCwT
// SIG // XWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEA
// SIG // AaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1Ud
// SIG // DgQWBBRIbmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEE
// SIG // AYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYw
// SIG // DwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToC
// SIG // MZBDuRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBL
// SIG // hklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
// SIG // bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
// SIG // MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEF
// SIG // BQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
// SIG // aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNf
// SIG // MjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcu
// SIG // AzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMu
// SIG // aHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABf
// SIG // AHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0AZQBuAHQA
// SIG // LiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou
// SIG // 09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+
// SIG // vj/oCso7v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzS
// SIG // Gksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlE
// SIG // PXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6V
// SIG // oCo/KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu
// SIG // 5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
// SIG // STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
// SIG // mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38c
// SIG // bxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
// SIG // pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7f
// SIG // QccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AA
// SIG // KcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74v2u3
// SIG // S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8
// SIG // MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7
// SIG // qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJ
// SIG // UnMTDXpQzTGCBKowggSmAgEBMIGVMH4xCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2Rl
// SIG // IFNpZ25pbmcgUENBIDIwMTECEzMAAADE6Yn4eoFQ6f8A
// SIG // AAAAAMQwCQYFKw4DAhoFAKCBvjAZBgkqhkiG9w0BCQMx
// SIG // DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYK
// SIG // KwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU+2mxhgnI
// SIG // t0WvYy9P733sZBsEoFcwXgYKKwYBBAGCNwIBDDFQME6g
// SIG // DIAKAEEAZABTAEQAS6E+gDxodHRwOi8vZWR3ZWIvc2l0
// SIG // ZXMvSVNTRW5naW5lZXJpbmcvRW5nRnVuL1NpdGVQYWdl
// SIG // cy9Ib21lLmFzcHgwDQYJKoZIhvcNAQEBBQAEggEANsQt
// SIG // MEeB3+Zu6i+ArdoytE9OOG2nQKqI5pu2NEGY4MrYLXsF
// SIG // fpGpq5qulmhX+Uc8rEFtKJrWW46eIGw05VXt4/w0EacD
// SIG // vANWcaL1oWq7ABQc9mwsJDRwwiQWshgk5Vg3XbvFYvbc
// SIG // PHnf16u/emj/jEE8TAJNZCnKfdSsMPylIDRBQcreX3vQ
// SIG // ExmXiPDbzIKyyre+HqEU7A80E/5criuqNDYC27aI59MM
// SIG // s6er8iAYb99ekoJXnsj8TwB8XqSpnY52NdtAf/obrpQO
// SIG // OfTOYMEMGnM/gPOw2xQ4Ca2F5RTyUQbnp6EwMY5UTE2V
// SIG // nQbCMRc+JMU6AygCpSsDvrKpD6qiYaGCAigwggIkBgkq
// SIG // hkiG9w0BCQYxggIVMIICEQIBATCBjjB3MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0ECEzMAAAC+pA/1yaUO4TAAAAAAAL4w
// SIG // CQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG
// SIG // 9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDQwNjAyMjU1
// SIG // NlowIwYJKoZIhvcNAQkEMRYEFJ9s4h+SKpYlHOOBjhu1
// SIG // RlCR0o++MA0GCSqGSIb3DQEBBQUABIIBABihEb9Tk/9/
// SIG // WG17H4IKCnmuB3n5zQf35lClYzSOlaXyhLg4n1OrsIMP
// SIG // f1CCJp07l56zX24W9Wcxv4wYDU1vUJaSolBvxwqx2hi+
// SIG // +Oo7X2EEN63civr/0QD8dgBYKa4ZxkoJwt+BuYzMIBvJ
// SIG // QqpSsCS7VZbuRdtLjKvFqhjAYs0lsvR+lWV/yEVLjbgr
// SIG // VIacZKXF+q99DezwnQyqyKYbIe/aSDIIptQ9ay7cfMeH
// SIG // ju+UccvkSn28dc0S/1uhxMCd4iQ56nDt3uXFEmOeWbfe
// SIG // r4gFd14XLvkMGwzoCVhue1lWWE2MqXiOznH80NhwV7ZB
// SIG // iYxwSF9zEAnO6M7eiKSPc4k=
// SIG // End signature block
